export interface Item {
  name: string
  image: string

  isFood: boolean
  foodCategory: string
  settlementDemand: number // per 1k pops per month

  isSurplusPossible: boolean
  possibleSurplusTargets: string[]
}

export const VIRTUAL_ITEM = {
  Demand: "Demand",
  Fertility: "Fertility",
} as const

const foodData: Item[] = [
  {
    name: "Potato",
    image: "",
    isFood: true,
    foodCategory: "Carbs",
    settlementDemand: 42,
    isSurplusPossible: true,
    possibleSurplusTargets: ["Animal Feed", "None"],
  },
  {
    name: "Corn",
    image: "",
    isFood: true,
    foodCategory: "Carbs",
    settlementDemand: 30,
    isSurplusPossible: true,
    possibleSurplusTargets: ["Ethanol", "Animal Feed", "None"],
  },
  {
    name: "Bread",
    image: "",
    isFood: true,
    foodCategory: "Carbs",
    settlementDemand: 20,
    isSurplusPossible: false,
    possibleSurplusTargets: [],
  },
  {
    name: "Meat",
    image: "",
    isFood: true,
    foodCategory: "Protein",
    settlementDemand: 27,
    isSurplusPossible: false,
    possibleSurplusTargets: [],
  },
  {
    name: "Eggs",
    image: "",
    isFood: true,
    foodCategory: "Protein",
    settlementDemand: 30,
    isSurplusPossible: false,
    possibleSurplusTargets: ["Food Pack", "None"],
  },
  {
    name: "Tofu",
    image: "",
    isFood: true,
    foodCategory: "Protein",
    settlementDemand: 18,
    isSurplusPossible: false,
    possibleSurplusTargets: [],
  },
  {
    name: "Sausage",
    image: "",
    isFood: true,
    foodCategory: "Protein",
    settlementDemand: 33.5,
    isSurplusPossible: false,
    possibleSurplusTargets: [],
  },
  {
    name: "Vegetables",
    image: "",
    isFood: true,
    foodCategory: "Vitamins",
    settlementDemand: 42,
    isSurplusPossible: true,
    possibleSurplusTargets: ["Food Pack", "None"],
  },
  {
    name: "Fruit",
    image: "",
    isFood: true,
    foodCategory: "Vitamins",
    settlementDemand: 31.5,
    isSurplusPossible: true,
    possibleSurplusTargets: ["None"],
  },
  {
    name: "Snack",
    image: "",
    isFood: true,
    foodCategory: "Treats",
    settlementDemand: 26,
    isSurplusPossible: false,
    possibleSurplusTargets: [],
  },
  {
    name: "Cake",
    image: "",
    isFood: true,
    foodCategory: "Treats",
    settlementDemand: 25,
    isSurplusPossible: false,
    possibleSurplusTargets: [],
  },
]

const itemData: Item[] = [
  {
    name: "Flour",
    image: "",
    isFood: false,
    foodCategory: "",
    settlementDemand: 0,
    isSurplusPossible: false,
    possibleSurplusTargets: [],
  },
  {
    name: "Wheat",
    image: "",
    isFood: false,
    foodCategory: "",
    settlementDemand: 0,
    isSurplusPossible: true,
    possibleSurplusTargets: ["Animal Feed", "None"],
  },
  {
    name: "Animal Feed",
    image: "",
    isFood: false,
    foodCategory: "",
    settlementDemand: 0,
    isSurplusPossible: false,
    possibleSurplusTargets: [],
  },
  {
    name: "Meat Trimmings",
    image: "",
    isFood: false,
    foodCategory: "",
    settlementDemand: 0,
    isSurplusPossible: false,
    possibleSurplusTargets: [],
  },
  {
    name: "Chicken Carcass",
    image: "",
    isFood: false,
    foodCategory: "",
    settlementDemand: 0,
    isSurplusPossible: false,
    possibleSurplusTargets: [],
  },
  {
    name: "Soybean",
    image: "",
    isFood: false,
    foodCategory: "",
    settlementDemand: 0,
    isSurplusPossible: true,
    possibleSurplusTargets: ["Diesel", "Animal Feed", "None"],
  },
  {
    name: "Cooking Oil",
    image: "",
    isFood: false,
    foodCategory: "",
    settlementDemand: 0,
    isSurplusPossible: false,
    possibleSurplusTargets: [],
  },
  {
    name: "Canola",
    image: "",
    isFood: false,
    foodCategory: "",
    settlementDemand: 0,
    isSurplusPossible: true,
    possibleSurplusTargets: ["Diesel", "None"],
  },
  {
    name: "Sugar",
    image: "",
    isFood: false,
    foodCategory: "",
    settlementDemand: 0,
    isSurplusPossible: false,
    possibleSurplusTargets: [],
  },
  {
    name: "Sugar Cane",
    image: "",
    isFood: false,
    foodCategory: "",
    settlementDemand: 0,
    isSurplusPossible: true,
    possibleSurplusTargets: ["Ethanol", "None"],
  },
  {
    name: "Medical Supplies",
    image: "",
    isFood: false,
    foodCategory: "",
    settlementDemand: 0,
    isSurplusPossible: false,
    possibleSurplusTargets: [],
  },
  {
    name: "Disinfectant",
    image: "",
    isFood: false,
    foodCategory: "",
    settlementDemand: 0,
    isSurplusPossible: false,
    possibleSurplusTargets: [],
  },
  {
    name: "Ethanol",
    image: "",
    isFood: false,
    foodCategory: "",
    settlementDemand: 0,
    isSurplusPossible: false,
    possibleSurplusTargets: [],
  },
  {
    name: "Corn Mash",
    image: "",
    isFood: false,
    foodCategory: "",
    settlementDemand: 0,
    isSurplusPossible: false,
    possibleSurplusTargets: [],
  },
  {
    name: "Medical Supplies II",
    image: "",
    isFood: false,
    foodCategory: "",
    settlementDemand: 0,
    isSurplusPossible: false,
    possibleSurplusTargets: [],
  },
  {
    name: "Antibiotics",
    image: "",
    isFood: false,
    foodCategory: "",
    settlementDemand: 0,
    isSurplusPossible: false,
    possibleSurplusTargets: [],
  },
  {
    name: "Medical Supplies III",
    image: "",
    isFood: false,
    foodCategory: "",
    settlementDemand: 0,
    isSurplusPossible: false,
    possibleSurplusTargets: [],
  },
  {
    name: "Morphine",
    image: "",
    isFood: false,
    foodCategory: "",
    settlementDemand: 0,
    isSurplusPossible: false,
    possibleSurplusTargets: [],
  },
  {
    name: "Poppy",
    image: "",
    isFood: false,
    foodCategory: "",
    settlementDemand: 0,
    isSurplusPossible: true,
    possibleSurplusTargets: ["None"],
  },
  {
    name: "Diesel",
    image: "",
    isFood: false,
    foodCategory: "",
    settlementDemand: 0,
    isSurplusPossible: false,
    possibleSurplusTargets: [],
  },
  {
    name: "Tree Sapling",
    image: "",
    isFood: false,
    foodCategory: "",
    settlementDemand: 0,
    isSurplusPossible: true,
    possibleSurplusTargets: ["None"],
  },
]

export const ALL_ITEMS: Item[] = [...foodData, ...itemData]

export const ITEM_BY_NAME = Object.fromEntries(
  ALL_ITEMS.map((item) => [item.name, item])
)

export const MEDICAL_SUPPLIES = {
  None: "None",
  MedicalSupplies: "Medical Supplies",
  MedicalSupplies2: "Medical Supplies II",
  MedicalSupplies3: "Medical Supplies III",
}
export type MedicalSupplies =
  (typeof MEDICAL_SUPPLIES)[keyof typeof MEDICAL_SUPPLIES]
