export interface Recipe {
  name: string
  factoryName: string
  cycleTime: number
  products: Map<string, number>
  ingredients: Map<string, number>
  requireItemUnlocked: string[]
  requireSurplusTarget: { [itemName: string]: string }
}

const productRecipeData: Recipe[] = [
  {
    name: "Produce Bread",
    factoryName: "Baking Unit",
    cycleTime: 30,
    products: new Map([["Bread", 12]]),
    ingredients: new Map([["Flour", 8]]),
    requireItemUnlocked: [],
    requireSurplusTarget: {},
  },
  {
    name: "Produce Flour",
    factoryName: "Mill",
    cycleTime: 30,
    products: new Map([
      ["Flour", 8],
      ["Animal Feed", 1],
    ]),
    ingredients: new Map([["Wheat", 8]]),
    requireItemUnlocked: [],
    requireSurplusTarget: {},
  },
  {
    name: "Produce Meat",
    factoryName: "Food Processor",
    cycleTime: 20,
    products: new Map([
      ["Meat", 5],
      ["Meat Trimmings", 2],
    ]),
    ingredients: new Map([["Chicken Carcass", 10]]),
    requireItemUnlocked: [],
    requireSurplusTarget: {},
  },
  {
    name: "Produce Meat Trimmings",
    factoryName: "Food Processor",
    cycleTime: 20,
    products: new Map([["Meat Trimmings", 9]]),
    ingredients: new Map([["Chicken Carcass", 10]]),
    requireItemUnlocked: [],
    requireSurplusTarget: {},
  },
  {
    name: "Produce Chicken Carcass",
    factoryName: "Chicken Farm",
    cycleTime: 60,
    products: new Map([
      ["Chicken Carcass", 10],
      ["Eggs", 7],
    ]),
    ingredients: new Map([["Animal Feed", 15]]),
    requireItemUnlocked: [],
    requireSurplusTarget: {},
  },
  {
    name: "Produce Eggs",
    factoryName: "Chicken Farm",
    cycleTime: 60,
    products: new Map([
      ["Chicken Carcass", 10],
      ["Eggs", 7],
    ]),
    ingredients: new Map([["Animal Feed", 15]]),
    requireItemUnlocked: [],
    requireSurplusTarget: {},
  },
  {
    name: "Produce Animal Feed from Corn",
    factoryName: "Mixer",
    cycleTime: 10,
    products: new Map([["Animal Feed", 12]]),
    ingredients: new Map([["Corn", 10]]),
    requireItemUnlocked: [],
    requireSurplusTarget: { Corn: "Animal Feed" },
  },
  {
    name: "Produce Animal Feed from Corn",
    factoryName: "Mixer II",
    cycleTime: 10,
    products: new Map([["Animal Feed", 24]]),
    ingredients: new Map([["Corn", 20]]),
    requireItemUnlocked: [],
    requireSurplusTarget: { Corn: "Animal Feed" },
  },
  {
    name: "Produce Animal Feed from Potato",
    factoryName: "Mixer",
    cycleTime: 10,
    products: new Map([["Animal Feed", 8]]),
    ingredients: new Map([["Potato", 10]]),
    requireItemUnlocked: [],
    requireSurplusTarget: { Potato: "Animal Feed" },
  },
  {
    name: "Produce Animal Feed from Potato",
    factoryName: "Mixer II",
    cycleTime: 10,
    products: new Map([["Animal Feed", 16]]),
    ingredients: new Map([["Potato", 20]]),
    requireItemUnlocked: [],
    requireSurplusTarget: { Potato: "Animal Feed" },
  },
  {
    name: "Produce Animal Feed from Soybean",
    factoryName: "Mixer",
    cycleTime: 10,
    products: new Map([["Animal Feed", 18]]),
    ingredients: new Map([["Soybean", 10]]),
    requireItemUnlocked: [],
    requireSurplusTarget: { Soybean: "Animal Feed" },
  },
  {
    name: "Produce Animal Feed from Soybean",
    factoryName: "Mixer II",
    cycleTime: 10,
    products: new Map([["Animal Feed", 36]]),
    ingredients: new Map([["Soybean", 20]]),
    requireItemUnlocked: [],
    requireSurplusTarget: { Soybean: "Animal Feed" },
  },
  {
    name: "Produce Animal Feed from Wheat",
    factoryName: "Mixer",
    cycleTime: 10,
    products: new Map([["Animal Feed", 16]]),
    ingredients: new Map([["Wheat", 10]]),
    requireItemUnlocked: [],
    requireSurplusTarget: { Wheat: "Animal Feed" },
  },
  {
    name: "Produce Animal Feed from Wheat",
    factoryName: "Mixer II",
    cycleTime: 10,
    products: new Map([["Animal Feed", 32]]),
    ingredients: new Map([["Wheat", 20]]),
    requireItemUnlocked: [],
    requireSurplusTarget: { Wheat: "Animal Feed" },
  },
  {
    name: "Produce Tofu",
    factoryName: "Food Processor",
    cycleTime: 40,
    products: new Map([
      ["Tofu", 8],
      ["Animal Feed", 3],
    ]),
    ingredients: new Map([["Soybean", 6]]),
    requireItemUnlocked: [],
    requireSurplusTarget: {},
  },
  {
    name: "Produce Sausage",
    factoryName: "Food Processor",
    cycleTime: 20,
    products: new Map([["Sausage", 8]]),
    ingredients: new Map([
      ["Meat Trimmings", 8],
      ["Flour", 2],
    ]),
    requireItemUnlocked: [],
    requireSurplusTarget: {},
  },
  {
    name: "Produce Snack from Corn",
    factoryName: "Food Processor",
    cycleTime: 20,
    products: new Map([["Snack", 16]]),
    ingredients: new Map([
      ["Corn", 8],
      ["Cooking Oil", 1],
    ]),
    requireItemUnlocked: [],
    requireSurplusTarget: {},
  },
  {
    name: "Produce Snack from Potato",
    factoryName: "Food Processor",
    cycleTime: 20,
    products: new Map([["Snack", 12]]),
    ingredients: new Map([
      ["Potato", 8],
      ["Cooking Oil", 1],
    ]),
    requireItemUnlocked: [],
    requireSurplusTarget: {},
  },
  {
    name: "Produce Cooking Oil from Canola",
    factoryName: "Mill",
    cycleTime: 30,
    products: new Map([
      ["Cooking Oil", 6],
      ["Animal Feed", 2],
    ]),
    ingredients: new Map([["Canola", 8]]),
    requireItemUnlocked: [],
    requireSurplusTarget: {},
  },
  {
    name: "Produce Cooking Oil from Soybean",
    factoryName: "Mill",
    cycleTime: 30,
    products: new Map([
      ["Cooking Oil", 3],
      ["Animal Feed", 4],
    ]),
    ingredients: new Map([["Soybean", 8]]),
    requireItemUnlocked: [],
    requireSurplusTarget: { Soybean: "Diesel" },
  },
  {
    name: "Produce Cake",
    factoryName: "Baking Unit",
    cycleTime: 30,
    products: new Map([["Cake", 7]]),
    ingredients: new Map([
      ["Flour", 5],
      ["Sugar", 2],
      ["Cooking Oil", 1],
      ["Eggs", 1],
      ["Fruit", 1],
    ]),
    requireItemUnlocked: [],
    requireSurplusTarget: {},
  },
  {
    name: "Produce Sugar",
    factoryName: "Food Processor",
    cycleTime: 40,
    products: new Map([["Sugar", 8]]),
    ingredients: new Map([["Sugar Cane", 10]]),
    requireItemUnlocked: ["Sugar Cane"],
    requireSurplusTarget: {},
  },
  {
    name: "Produce Medical Supplies with Assembly III",
    factoryName: "Assembly III",
    cycleTime: 20,
    products: new Map([["Medical Supplies", 8]]),
    ingredients: new Map([["Disinfectant", 4]]),
    requireItemUnlocked: [],
    requireSurplusTarget: {},
  },
  {
    name: "Produce Medical Supplies with Assembly IV",
    factoryName: "Assembly IV",
    cycleTime: 10,
    products: new Map([["Medical Supplies", 8]]),
    ingredients: new Map([["Disinfectant", 4]]),
    requireItemUnlocked: [],
    requireSurplusTarget: {},
  },
  {
    name: "Produce Medical Supplies with Assembly V",
    factoryName: "Assembly V",
    cycleTime: 10,
    products: new Map([["Medical Supplies", 16]]),
    ingredients: new Map([["Disinfectant", 8]]),
    requireItemUnlocked: [],
    requireSurplusTarget: {},
  },
  {
    name: "Produce Disinfectant with Chemical Plant",
    factoryName: "Chemical Plant",
    cycleTime: 40,
    products: new Map([["Disinfectant", 8]]),
    ingredients: new Map([["Ethanol", 3]]),
    requireItemUnlocked: [],
    requireSurplusTarget: {},
  },
  {
    name: "Produce Disinfectant with Chemical Plant II",
    factoryName: "Chemical Plant II",
    cycleTime: 20,
    products: new Map([["Disinfectant", 8]]),
    ingredients: new Map([["Ethanol", 3]]),
    requireItemUnlocked: [],
    requireSurplusTarget: {},
  },
  {
    name: "Produce Ethanol from Corn Mash",
    factoryName: "Fermentation Tank",
    cycleTime: 30,
    products: new Map([["Ethanol", 4]]),
    ingredients: new Map([["Corn Mash", 6]]),
    requireItemUnlocked: [],
    requireSurplusTarget: {},
  },
  {
    name: "Produce Ethanol from Sugar",
    factoryName: "Fermentation Tank",
    cycleTime: 30,
    products: new Map([["Ethanol", 6]]),
    ingredients: new Map([["Sugar", 8]]),
    requireItemUnlocked: [],
    requireSurplusTarget: {},
  },
  {
    name: "Produce Corn Mash",
    factoryName: "Mill",
    cycleTime: 40,
    products: new Map([["Corn Mash", 6]]),
    ingredients: new Map([["Corn", 8]]),
    requireItemUnlocked: [],
    requireSurplusTarget: {},
  },
  {
    name: "Produce Medical Supplies II with Assembly III",
    factoryName: "Assembly III",
    cycleTime: 20,
    products: new Map([["Medical Supplies II", 8]]),
    ingredients: new Map([
      ["Medical Supplies", 8],
      ["Antibiotics", 4],
    ]),
    requireItemUnlocked: [],
    requireSurplusTarget: {},
  },
  {
    name: "Produce Medical Supplies II with Assembly IV",
    factoryName: "Assembly IV",
    cycleTime: 10,
    products: new Map([["Medical Supplies II", 8]]),
    ingredients: new Map([
      ["Medical Supplies", 8],
      ["Antibiotics", 4],
    ]),
    requireItemUnlocked: [],
    requireSurplusTarget: {},
  },
  {
    name: "Produce Medical Supplies II with Assembly V",
    factoryName: "Assembly V",
    cycleTime: 10,
    products: new Map([["Medical Supplies II", 16]]),
    ingredients: new Map([
      ["Medical Supplies", 16],
      ["Antibiotics", 8],
    ]),
    requireItemUnlocked: [],
    requireSurplusTarget: {},
  },
  {
    name: "Produce Antibiotics",
    factoryName: "Fermentation Tank",
    cycleTime: 60,
    products: new Map([["Antibiotics", 8]]),
    ingredients: new Map([["Sugar", 4]]),
    requireItemUnlocked: [],
    requireSurplusTarget: {},
  },
  {
    name: "Produce Medical Supplies III with Assembly III",
    factoryName: "Assembly III",
    cycleTime: 20,
    products: new Map([["Medical Supplies III", 8]]),
    ingredients: new Map([
      ["Medical Supplies II", 8],
      ["Morphine", 4],
    ]),
    requireItemUnlocked: [],
    requireSurplusTarget: {},
  },
  {
    name: "Produce Medical Supplies III with Assembly IV",
    factoryName: "Assembly IV",
    cycleTime: 10,
    products: new Map([["Medical Supplies III", 8]]),
    ingredients: new Map([
      ["Medical Supplies II", 8],
      ["Morphine", 4],
    ]),
    requireItemUnlocked: [],
    requireSurplusTarget: {},
  },
  {
    name: "Produce Medical Supplies III with Assembly V",
    factoryName: "Assembly V",
    cycleTime: 10,
    products: new Map([["Medical Supplies III", 16]]),
    ingredients: new Map([
      ["Medical Supplies II", 16],
      ["Morphine", 8],
    ]),
    requireItemUnlocked: [],
    requireSurplusTarget: {},
  },
  {
    name: "Produce Morphine",
    factoryName: "Chemical Plant II",
    cycleTime: 20,
    products: new Map([["Morphine", 8]]),
    ingredients: new Map([["Poppy", 4]]),
    requireItemUnlocked: [],
    requireSurplusTarget: {},
  },
  {
    name: "Produce Diesel from Cooking Oil",
    factoryName: "Chemical Plant",
    cycleTime: 40,
    products: new Map([["Diesel", 18]]),
    ingredients: new Map([
      ["Ethanol", 5],
      ["Cooking Oil", 10],
    ]),
    requireItemUnlocked: [],
    requireSurplusTarget: {},
  },
  {
    name: "Produce Diesel from Cooking Oil",
    factoryName: "Chemical Plant II",
    cycleTime: 20,
    products: new Map([["Diesel", 18]]),
    ingredients: new Map([
      ["Ethanol", 5],
      ["Cooking Oil", 10],
    ]),
    requireItemUnlocked: [],
    requireSurplusTarget: {},
  },
]

const farmingRecipeData: Recipe[] = [
  {
    name: "Produce Canola",
    factoryName: "Farm",
    cycleTime: 180,
    products: new Map([["Canola", 26]]),
    ingredients: new Map([["Fertility", 0.27]]),
    requireItemUnlocked: [],
    requireSurplusTarget: {},
  },
  {
    name: "Produce Canola",
    factoryName: "Greenhouse",
    cycleTime: 180,
    products: new Map([["Canola", 33]]),
    ingredients: new Map([["Fertility", 0.3]]),
    requireItemUnlocked: [],
    requireSurplusTarget: {},
  },
  {
    name: "Produce Canola",
    factoryName: "Greenhouse II",
    cycleTime: 180,
    products: new Map([["Canola", 39]]),
    ingredients: new Map([["Fertility", 0.34]]),
    requireItemUnlocked: [],
    requireSurplusTarget: {},
  },
  {
    name: "Produce Poppy",
    factoryName: "Greenhouse",
    cycleTime: 240,
    products: new Map([["Poppy", 25]]),
    ingredients: new Map([["Fertility", 0.4]]),
    requireItemUnlocked: [],
    requireSurplusTarget: {},
  },
  {
    name: "Produce Poppy",
    factoryName: "Greenhouse II",
    cycleTime: 240,
    products: new Map([["Poppy", 30]]),
    ingredients: new Map([["Fertility", 0.45]]),
    requireItemUnlocked: [],
    requireSurplusTarget: {},
  },
  {
    name: "Produce Potato",
    factoryName: "Farm",
    cycleTime: 180,
    products: new Map([["Potato", 58]]),
    ingredients: new Map([["Fertility", 0.32]]),
    requireItemUnlocked: [],
    requireSurplusTarget: {},
  },
  {
    name: "Produce Potato",
    factoryName: "Greenhouse",
    cycleTime: 180,
    products: new Map([["Potato", 73]]),
    ingredients: new Map([["Fertility", 0.35]]),
    requireItemUnlocked: [],
    requireSurplusTarget: {},
  },
  {
    name: "Produce Potato",
    factoryName: "Greenhouse II",
    cycleTime: 180,
    products: new Map([["Potato", 87]]),
    ingredients: new Map([["Fertility", 0.39]]),
    requireItemUnlocked: [],
    requireSurplusTarget: {},
  },
  {
    name: "Produce Vegetables",
    factoryName: "Farm",
    cycleTime: 240,
    products: new Map([["Vegetables", 60]]),
    ingredients: new Map([["Fertility", 0.42]]),
    requireItemUnlocked: [],
    requireSurplusTarget: {},
  },
  {
    name: "Produce Vegetables",
    factoryName: "Greenhouse",
    cycleTime: 240,
    products: new Map([["Vegetables", 75]]),
    ingredients: new Map([["Fertility", 0.47]]),
    requireItemUnlocked: [],
    requireSurplusTarget: {},
  },
  {
    name: "Produce Vegetables",
    factoryName: "Greenhouse II",
    cycleTime: 240,
    products: new Map([["Vegetables", 90]]),
    ingredients: new Map([["Fertility", 0.52]]),
    requireItemUnlocked: [],
    requireSurplusTarget: {},
  },
  {
    name: "Produce Soybean",
    factoryName: "Farm",
    cycleTime: 240,
    products: new Map([["Soybean", 22]]),
    ingredients: new Map([["Fertility", 0.6]]),
    requireItemUnlocked: [],
    requireSurplusTarget: {},
  },
  {
    name: "Produce Soybean",
    factoryName: "Greenhouse",
    cycleTime: 240,
    products: new Map([["Soybean", 28]]),
    ingredients: new Map([["Fertility", 0.68]]),
    requireItemUnlocked: [],
    requireSurplusTarget: {},
  },
  {
    name: "Produce Soybean",
    factoryName: "Greenhouse II",
    cycleTime: 240,
    products: new Map([["Soybean", 33]]),
    ingredients: new Map([["Fertility", 0.75]]),
    requireItemUnlocked: [],
    requireSurplusTarget: {},
  },
  {
    name: "Produce Corn",
    factoryName: "Farm",
    cycleTime: 240,
    products: new Map([["Corn", 66]]),
    ingredients: new Map([["Fertility", 0.48]]),
    requireItemUnlocked: [],
    requireSurplusTarget: {},
  },
  {
    name: "Produce Corn",
    factoryName: "Greenhouse",
    cycleTime: 240,
    products: new Map([["Corn", 83]]),
    ingredients: new Map([["Fertility", 0.54]]),
    requireItemUnlocked: [],
    requireSurplusTarget: {},
  },
  {
    name: "Produce Corn",
    factoryName: "Greenhouse II",
    cycleTime: 240,
    products: new Map([["Corn", 99]]),
    ingredients: new Map([["Fertility", 0.6]]),
    requireItemUnlocked: [],
    requireSurplusTarget: {},
  },
  {
    name: "Produce Wheat",
    factoryName: "Farm",
    cycleTime: 360,
    products: new Map([["Wheat", 58]]),
    ingredients: new Map([["Fertility", 0.63]]),
    requireItemUnlocked: [],
    requireSurplusTarget: {},
  },
  {
    name: "Produce Wheat",
    factoryName: "Greenhouse",
    cycleTime: 360,
    products: new Map([["Wheat", 73]]),
    ingredients: new Map([["Fertility", 0.71]]),
    requireItemUnlocked: [],
    requireSurplusTarget: {},
  },
  {
    name: "Produce Wheat",
    factoryName: "Greenhouse II",
    cycleTime: 360,
    products: new Map([["Wheat", 87]]),
    ingredients: new Map([["Fertility", 0.79]]),
    requireItemUnlocked: [],
    requireSurplusTarget: {},
  },
  {
    name: "Produce Fruit",
    factoryName: "Greenhouse",
    cycleTime: 480,
    products: new Map([["Fruit", 100]]),
    ingredients: new Map([["Fertility", 0.81]]),
    requireItemUnlocked: [],
    requireSurplusTarget: {},
  },
  {
    name: "Produce Fruit",
    factoryName: "Greenhouse II",
    cycleTime: 480,
    products: new Map([["Fruit", 120]]),
    ingredients: new Map([["Fertility", 0.9]]),
    requireItemUnlocked: [],
    requireSurplusTarget: {},
  },
  {
    name: "Produce Sugar Cane",
    factoryName: "Greenhouse",
    cycleTime: 540,
    products: new Map([["Sugar Cane", 220]]),
    ingredients: new Map([["Fertility", 1.52]]),
    requireItemUnlocked: [],
    requireSurplusTarget: {},
  },
  {
    name: "Produce Sugar Cane",
    factoryName: "Greenhouse II",
    cycleTime: 540,
    products: new Map([["Sugar Cane", 264]]),
    ingredients: new Map([["Fertility", 1.69]]),
    requireItemUnlocked: [],
    requireSurplusTarget: {},
  },
]

export function getRecipesOfFactories(
  availableFactoryNames: string[]
): Recipe[] {
  return productRecipeData.filter((recipe) =>
    availableFactoryNames.includes(recipe.factoryName)
  )
}

export function getFarmingRecipesOfFarm(farmVariant: string): Recipe[] {
  return farmingRecipeData.filter(
    (recipe) => recipe.factoryName === farmVariant
  )
}

export const ALL_RECIPE = [...productRecipeData, ...farmingRecipeData]
